source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'ShareOne_Example', :exclusive => true do
  pod "ShareOne", :path => "../"
end

target 'ShareOne_Tests', :exclusive => true do
  pod "ShareOne", :path => "../"

end
