source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ShareOne_Example', :exclusive => true do
  pod "ShareOne", :path => "../"
end

target 'ShareOne_Tests', :exclusive => true do
  pod "ShareOne", :path => "../"

  
end
