source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'ShareOne_Example', :exclusive => true do
  pod "ShareOne", :path => "../"
end

target 'ShareOne_Tests', :exclusive => true do
  pod "ShareOne", :path => "../"

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end